/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Flower.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['hibiscus_flower-Mesh'].geometry} material={materials.red} />
      <mesh geometry={nodes['hibiscus_flower-Mesh_1'].geometry} material={materials.hay} />
      <mesh geometry={nodes['hibiscus_flower-Mesh_2'].geometry} material={materials.tree} />
    </group>
  )
}

useGLTF.preload('/Flower.glb')
